### PR TITLE
Fix metadata null exceptions

### LINKED ISSUE #178: Fix the add command not adding person issue
The original add command didn't show up about the wrong command format, and everything couldn't work after a/address. 

No successful add a person or wrong command format. Only if the user types whole command: 
` add n/Name p/Phone e/Email r/Role d/Metadata c/CCA` then it could work.

Since no new features are not allowed, only fix the bug that pop-up wrong command format

### PR DESCRIPTION
**Pull request by JuliaPoo**
I attempted to manually find and handle null exceptions stemming from the optional argument in `AddCommand`, however, I soon gave up and decided to change `Person.metadata` into and `Optional` and let the type system tell me what to change.

Fixes #178 #153 #147 #142 #139 #137 #134 #126

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -34,13 +35,13 @@ public class Person {
     private final Attendance attendance;
     private final Sessions sessions;
 
-    private final Metadata metadata;
+    private final Optional<Metadata> metadata;
 
     /**
-     * Every field must be present and not null.
+     * Every field must be present and not null exception optional fields
```
Comment (Fidget-Spinner) [inline src/main/java/seedu/address/model/person/Person.java:41]: Technically a Optional<> also shouldn't be null. So this is correct.
```suggestion
     * Every field must be present and not null
```

**Review by Fidget-Spinner — COMMENTED** [review]
One minor comment

File: src/main/java/seedu/address/model/person/Person.java (hunk 1 above)
Comment (JuliaPoo) [reply src/main/java/seedu/address/model/person/Person.java]: Ohh there's a commit suggestion option that I now just noticed, anyways I've updated it.

**Review by Fidget-Spinner — APPROVED** [review]
